//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleMandu.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_productDetail
    {
        public int PID { get; set; }
        public string email { get; set; }
        public string mobile_number { get; set; }
        public string product_name { get; set; }
        public string product_location { get; set; }
        public string product_price { get; set; }
        public string product_description { get; set; }
        public string condition { get; set; }
        public string home_delivery { get; set; }
        public string warranty_type { get; set; }
        public string color { get; set; }
        public string features { get; set; }
        public string make_year { get; set; }
        public string bought_time { get; set; }
        public string type { get; set; }
        public string image { get; set; }
    }
}
